base_topic: /synchronized/
cameras:
    - {image_base_topic: left/, image_topic: image_raw, info_topic: camera_info}
    - {image_base_topic: right/, image_topic: image_raw, info_topic: camera_info}

# transform Body-Cameras
T_BC:
#    translation: [0.0, 0.0, 0.0]
#    quaternion:  [0.0, -0.0, 0.0, 1.0]
    translation: [0.012, 0.098, -0.022]
    quaternion:  [0.5, -0.5, 0.5, 0.5]

# tranform Body-Sensor (IMU)
T_BS:
    translation: [0.0, 0.0, 0.0]
    quaternion:  [0.0, -0.707106781186547, 0.0, 0.707106781186547]

imu:
    - {imu_topic: imu}

imu_params:
    sigma_g_c: 8.0e-4
    sigma_a_c: 8.0e-3
    sigma_gw_c: 8.0e-5
    sigma_aw_c: 4.0e-4
    tau: 360.0
    g: 9.806

# use the IMU at all?
useImu: true

# detection threshold
detectionThreshold: 62.0

# delay of images [ms]
imageDelay: -0.023
