base_topic: /
cameras:
    - {image_base_topic: cam2/, image_topic: image_raw, info_topic: camera_info,
       T_SC:
       [-0.00139745, 0.999998,     0.00107193,   0.0008,
        -0.424216,   0.000377874, -0.905561,    -0.2059,
        -0.90556,   -0.0017202,    0.42421,      0.0023,
         0.0,        0.0,          0.0,          1.0],
       #[  0.0,                 1.0,                   0.0,                  0.0008,
       #  -0.4226182617407,     0.0,                  -0.9063077870367,     -0.2059,
       #  -0.9063077870367,     0.0,                   0.4226182617407,      0.0023,
       #   0.0,                 0.0,                   0.0,                  1.0],
       image_dimension: [752, 480],
       distortion_coefficients: [-0.437380, 0.210360, 0.000581, 0.001087 ],
       distortion_type: radialtangential,
       focal_length: [623.298096, 621.344253],
       principal_point: [382.019392, 234.989798]}

# FLIR Tau integreation still TODO...
# T_SC1_tau =
#         1    0                       0                     0.5
#         0    0.422618261740699          -0.906307787036650  -174.9
#         0    0.906307787036650       0.422618261740699    24.9
#         0    0                       0                     1.0
#T_C1C2 =
#    0.0000    1.0000         0         0
#   -1.0000    0.0000         0         0
#         0         0    1.0000         0
#         0         0         0    1.0000

camera_params:
    camera_rate: 20
    sigma_absolute_translation:  0.0 #1.0e-10
    sigma_absolute_orientation:  0.0 #1.0e-3
    sigma_c_relative_translation: 0.0 #1.0e-6 # below 1.0e-6 ruines numerics...
    sigma_c_relative_orientation: 0.0 #1.0e-6 # below 1.0e-6 ruines numerics...

# tranform Body-Sensor (IMU)
T_BS:
    [1.0000, 0.0000, 0.0000, 0.0000,
     0.0000, 1.0000, 0.0000, 0.0000,
     0.0000, 0.0000, 1.0000, 0.0000,
     0.0000, 0.0000, 0.0000, 1.0000]

imu:
    - {imu_topic: imu0}

imu_params:
    a_max: 176.0 #m/s^2
    g_max: 7.8 #rad/s
    sigma_g_c: 12.0e-4 #6.0e-4
    sigma_a_c: 8.0e-3 #2.0e-3
    sigma_gw_c: 4.0e-6 #3.0e-6
    sigma_aw_c: 2.0e-5 #2.0e-5
    tau: 3600.0
    g: 9.81007
    a0: [ 0.0, -0.0, 0.00 ]
    #[09:49:28] Joern: accelerometer_noise_density: 1.7e-3, accelerometer_random_walk: 6.3895e-005,
    imu_rate: 200
#gyroscope_noise_density: 0.2e-3, gyroscope_random_walk: 2.8577e-006

magnetometer_params:
    stdev: 2.0                           # measurement (white noise part) stdev [uT]
    biasPriorStdev: 5.0                  # prior [uT]
    zDistortionPriorStdev: 2.0           # prior [uT]
    tau_bias: 100.0                     # reversion time constant of bias [s]
    tau_zDistortion: 1000.0               # reversion time constant of z-component [s]
    biasDiffNoiseDensity: 1.0e-2         # bias noise density [uT/sqrt(Hz)]
    zDistortionDiffNoiseDensity: 1.0e-4  # z-component noise density [uT/sqrt(Hz)]

# use the IMU at all?
useImu: true

# VIO window parameters
numKeyframes: 5
numImuFrames: 3

# detection
detectionThreshold: 40.0
detectionOctaves: 0

# delay of images [s]: -8ms with zero-order hold integration at 200 Hz: makes sense.
imageDelay: -0.00 # -0.0055 without Joern's awesome synchronization, 0 otherwise

# display Images?
displayImages: true

# use direct driver
useDriver: false

# save optimization to disk
saveGraphs: false

# rate at which odometry updates are published
# only works properly if imu_rate/publish_rate is an integer!!
publish_rate: 200
