%YAML:1.0
cameras:
     - {T_SC:
        [ 0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
          0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
          -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
           0.0, 0.0, 0.0, 1.0],
        image_dimension: [752, 480],
        distortion_coefficients: [-0.28340811217, 0.0739590738929, 0.000193595028569, 1.76187114545e-05],
        distortion_type: radialtangential,
        focal_length: [458.654880721, 457.296696463],
        principal_point: [367.215803962, 248.37534061]}

     - {T_SC:
        [ 0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
          0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
          -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
           0.0, 0.0, 0.0, 1.0],
        image_dimension: [752, 480],
        distortion_coefficients: [-0.283683654496, 0.0745128430929, -0.000104738949098, -3.55590700274e-05],
        distortion_type: radialtangential,
        focal_length: [457.587426604, 456.13442556],
        principal_point: [379.99944652, 255.238185386]}


camera_params:
    camera_rate: 20
    sigma_absolute_translation: 0.0 #1.0e-8
    sigma_absolute_orientation: 0.0 #1.0e-3
    sigma_c_relative_translation: 0.0 #1.0e-6 # below 1.0e-6 ruines numerics...
    sigma_c_relative_orientation: 0.0 #1.0e-6 # below 1.0e-6 ruines numerics...
    timestamp_tolerance: 0.005 # seconds

# tranform Body-Sensor (IMU)
T_BS:
    [1.0000, 0.0000, 0.0000, 0.0000,
     0.0000, 1.0000, 0.0000, 0.0000,
     0.0000, 0.0000, 1.0000, 0.0000,
     0.0000, 0.0000, 0.0000, 1.0000]

imu_params:
    a_max: 176.0 #m/s^2
    g_max: 7.8 #rad/s
    sigma_g_c: 12.0e-4 #6.0e-4
    sigma_a_c: 8.0e-3 #2.0e-3
    sigma_gw_c: 3.0e-6 #3.0e-6
    sigma_aw_c: 2.0e-5 #2.0e-5
    tau: 3600.0
    g: 9.81007
    a0: [ 0.0, -0.0, 0.00 ]
    #[09:49:28] Joern: accelerometer_noise_density: 1.7e-3, accelerometer_random_walk: 6.3895e-005,
    imu_rate: 800
#gyroscope_noise_density: 0.2e-3, gyroscope_random_walk: 2.8577e-006

# dummy magnetometer
magnetometer_params:
    stdev: 2.0                           # measurement (white noise part) stdev [uT]
    biasPriorStdev: 5.0                  # prior [uT]
    zDistortionPriorStdev: 2.0           # prior [uT]
    tau_bias: 100.0                     # reversion time constant of bias [s]
    tau_zDistortion: 1000.0               # reversion time constant of z-component [s]
    biasDiffNoiseDensity: 1.0e-2         # bias noise density [uT/sqrt(Hz)]
    zDistortionDiffNoiseDensity: 1.0e-4  # z-component noise density [uT/sqrt(Hz)]

# use the IMU at all?
useImu: true

# VIO window parameters
numKeyframes: 5
numImuFrames: 3

# ceres optimization options
ceres_options:
    minIterations: 3
    maxIterations: 10
    timeLimit: 0.025      # [s] negative values will set the an unlimited time limit

# detection
detectionThreshold: 40.0
detectionOctaves: 0

# delay of images [s]: -8ms with zero-order hold integration at 200 Hz: makes sense.
imageDelay: 0.0 # -0.0055 without Joern's awesome synchronization, 0 otherwise

# display Images?
displayImages: true

# use direct driver
useDriver: false

# save optimization to disk
saveGraphs: false

# rate at which odometry updates are published
# only works properly if imu_rate/publish_rate is an integer!!
publish_rate: 800

publishing_options:
    landmarkQualityThreshold: 1.0e-5     # landmark with lower quality will not be published
    maximumLandmarkQuality: 0.05         # landmark with higher quality will be published with the maximum colour intensity
    maxPathLength: 20                    # maximum length of the published path
    publishImuPropagatedState: true      # publish state after each processed IMU measurement instead of after each processed image
