<?xml version='1.0'?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Transform world to rectangle (0 0 0)' -->
  <xacro:property name="p1_wrld_x" value="$(arg p1_wrld_x)"/>
  <xacro:property name="p1_wrld_y" value="$(arg p1_wrld_y)"/>
  <xacro:property name="p1_wrld_z" value="$(arg p1_wrld_z)"/>
  <xacro:property name="yaw" value="$(arg yaw)"/>

  <!-- p3 in rectangle coordinates -->
  <xacro:property name="p3_rct_x" value="$(arg p3_rct_x)"/>
  <xacro:property name="p3_rct_y" value="$(arg p3_rct_y)"/>
  <xacro:property name="frame_width" value="$(arg frame_width)"/>

  <!-- Wall settings-->
  <xacro:property name="wall_name" value="$(arg wall_name)"/>
  <xacro:property name="wall_width" value="$(arg wall_width)"/>
  <xacro:property name="wall_height" value="$(arg wall_height)"/>
  <xacro:property name="wall_depth" value="$(arg wall_depth)"/>

  <xacro:property name="frame_depth" value="0.01" />

  <!-- Wall center in relatvie to rectangle 0/0/0 -->
  <xacro:property name="wall_center_rct_x" value="${p3_rct_x/2}" />
  <xacro:property name="wall_center_rct_y" value="${wall_depth/2.0}" />
  <xacro:property name="wall_center_rct_z" value="${wall_height/2-p1_wrld_z}" />

 <!-- Align model with rectangle 0/0/0 -->
 <origin xyz="${p1_wrld_x} ${p1_wrld_y} ${p1_wrld_z}" rpy="0 0 ${yaw}" />


 <!-- Main Wall -->
 <link name="${wall_name}/main">
      <inertial>
          <origin xyz="${wall_center_rct_x} ${wall_center_rct_y} ${wall_center_rct_z}" rpy="0 0 0" />
          <mass value="1.0" />
          <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"  iyy="100.0"  iyz="0.0"  izz="1.0" />
      </inertial>
      <collision name="collision">
        <origin xyz="${wall_center_rct_x} ${wall_center_rct_y} ${wall_center_rct_z}" rpy="0 0 0" /> 
        <geometry>
          <box size="${wall_width} ${wall_depth} ${wall_height}" />
        </geometry>
      </collision>
      <visual>
        <origin xyz="${wall_center_rct_x} ${wall_center_rct_y} ${wall_center_rct_z}" rpy="0 0 0" />
        <geometry>
          <box size="${wall_width} ${wall_depth} ${wall_height}" />
        </geometry>
      </visual>
  </link>


<!-- Frame elements -->
  <link  name="${wall_name}/frame_top">
    <visual>
      <origin xyz="${p3_rct_x/2.0}  ${-frame_depth/2} ${p3_rct_y-frame_width/2}" />
      <cast_shadows>false</cast_shadows>
      <geometry>
        <box size="${p3_rct_x} 0.02 ${frame_width}" />
      </geometry>   
    </visual>
  </link>

  <link  name="${wall_name}/frame_bottom">
    <visual>
      <origin xyz="${p3_rct_x/2.0}  ${-frame_depth/2} ${frame_width/2}" />
      <cast_shadows>false</cast_shadows>
      <geometry>
        <box size="${p3_rct_x} 0.02 ${frame_width}" />
      </geometry>   
    </visual>
  </link>

  <link  name="${wall_name}/frame_left">
    <visual>
      <origin xyz="${frame_width/2}  ${-frame_depth/2} ${p3_rct_y/2}" />
      <cast_shadows>false</cast_shadows>
      <geometry>
        <box size="${frame_width} 0.02 ${p3_rct_y}" />
      </geometry>   
    </visual>
  </link>

  <link  name="${wall_name}/frame_right">
    <visual>
      <origin xyz="${p3_rct_x-frame_width/2}  ${-frame_depth/2} ${p3_rct_y/2}" />
      <cast_shadows>false</cast_shadows>
      <geometry>
        <box size="${frame_width} 0.02 ${p3_rct_y}" />
      </geometry>   
    </visual>
  </link>

<!-- Fixed joints -->
  <joint name="${wall_name}_joint1" type="fixed">
   <parent link="${wall_name}/main"/>
   <child link="${wall_name}/frame_top"/>
  </joint>

  <joint name="${wall_name}_joint2" type="fixed">
   <parent link="${wall_name}/main"/>
   <child link="${wall_name}/frame_bottom"/>
  </joint>

  <joint name="${wall_name}_joint3" type="fixed">
   <parent link="${wall_name}/main"/>
   <child link="${wall_name}/frame_left"/>
  </joint>

  <joint name="${wall_name}_joint4" type="fixed">
   <parent link="${wall_name}/main"/>
   <child link="${wall_name}/frame_right"/>
  </joint>

<!-- Material definition -->
  <gazebo reference="${wall_name}/main">
    <material>
    configurable_wall/RoughWall
    </material>
  </gazebo>

  <gazebo reference="${wall_name}/frame_top">
    <material>
    configurable_wall/NonReflectiveBlack
    </material>
  </gazebo>
  <gazebo reference="${wall_name}/frame_bottom">
    <material>
    configurable_wall/NonReflectiveBlack
    </material>
  </gazebo>
  <gazebo reference="${wall_name}/frame_left">
    <material>
    configurable_wall/NonReflectiveBlack
    </material>
  </gazebo>
  <gazebo reference="${wall_name}/frame_right">
    <material>
    configurable_wall/NonReflectiveBlack
    </material>
  </gazebo> 

</robot>

